name: Steak Appreciation Society
favicon: null
layout_spectrum: 0.24346
typography_spectrum: 0.08902645297348499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1819'
    - '#4e4a4b'
    - '#8c898a'
    - '#c1bfc0'
  brandStrength: 0.7090847992803901
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
